# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Casa Múcaro
tagline:          Impresiones3D
description:      Bitácora de Impresión
url:              http://casa-mucaro.github.io/Impresiones3D
baseurl:          

#underscored folder are ignored by jekyll at build time
include: _assets

author:
  name:           Casa Múcaro
  url:            

paginate: 5

# Custom vars
version:     
     
github:           
  repo:           https://github.com/Casa-Mucaro/Impresiones3D

