# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Casa Múcaro
tagline:          Impresiones3D
description:      Bitácora de Impresión
url:              https://github.com/Casa-Mucaro/Impresiones3D
baseurl:          /Impresiones3D/

author:
  name:           Casa Múcaro
  url:            

paginate: 5

# Custom vars
version:     
     
github:           
  repo:           https://github.com/Casa-Mucaro/Impresiones3D

