# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Impresiones3D
tagline:          ''
description:      'En estos momentos tenemos dos proyectos principales corriendo en paralelo: la creación de nuevos instrumentos músicales y, el otro, generar mecanismos de movimiento para títeres de mesa (por ahora).'
url:              https://github.com/Casa-Mucaro/Impresiones3D

author:
  name:           'Casa Múcaro'
  url:            http://casamucaro.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           
