# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Impresiones3D
tagline:          ''
description:      'A brazen two-cumn <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://github.com/Casa-Mucaro/Impresiones3D

author:
  name:           'Casa Múcaro'
  url:            http://casamucaro.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           
